apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4= # Username in base64
  mongo-root-password: YWRtaW4= # Passwort
  mongo-init-database: ZGJfd2VhdGhlcg== # db_weather
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongo-service #Name vom Service, welcher für die DB zustänsig ist
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: speicher
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage
spec:
  storageClassName: speicher
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb #Containername
          image: mongo
          ports:
          - containerPort: 27017
          volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: MONGO_INITDB_DATABASE
            valueFrom: 
              secretKeyRef:
                name: mongodb-secret
                key: mongo-init-database
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb # Link zu Pod (Label bei Deployment and pod)
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017