apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: lucakoester/lk-bachelor-webserver:v1
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`caas.lk-bachelor.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: nginx-service
          namespace: default
          port: 80
  tls:
    certResolver: letsencrypt
