# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: silver
# provisioner: kubernetes.io/gce-pd
# volumeBindingMode: Immediate
# allowVolumeExpansion: true
# reclaimPolicy: Delete
# parameters:
#   type: pd-standard
#   fstype: ext4
#   replication-type: none
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: webapps-storage
# spec:
#   storageClassName: silver
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: lucakoester/lk-bachelor-webserver:v1
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 80
      #   volumeMounts:
      #   - name: webapps-storage
      #     mountPath: /usr/share/nginx/html
      # volumes:
      # - name: webapps-storage
      #   persistentVolumeClaim:
      #     claimName: webapps-storage
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`caas.lk-bachelor.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: nginx-service
          namespace: default
          port: 80
  tls:
    certResolver: letsencrypt
